version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    command: ["serve"]
    environment:
      NVIDIA_VISIBLE_DEVICES: "0,1"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docqa-api
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: qwen3:30b-instruct #qwen3:30b-instruct
      LLM_NUM_CTX: "8192"
      LLM_NUM_GPU: "999"
      STORAGE_DIR: /app/storage
    volumes:
      - ./:/app
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--workers","1"] # ["sleep", "infinity"] 
    restart: unless-stopped

volumes:
  ollama:
